// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdHgVoszZRnpgy7sJuBktS5pZNcYGwjjo',
    appId: '1:759792061333:web:5b0a688f1dd9f470a9049c',
    messagingSenderId: '759792061333',
    projectId: 'academic-advisor-assistant-db',
    authDomain: 'academic-advisor-assistant-db.firebaseapp.com',
    storageBucket: 'academic-advisor-assistant-db.appspot.com',
    databaseURL: "https://academic-advisor-assistant-db-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6FvWojg_NjeYXJGX1xT6uvDrr-lgQmxg',
    appId: '1:759792061333:android:8c0fc0c3ca6a2cd5a9049c',
    messagingSenderId: '759792061333',
    projectId: 'academic-advisor-assistant-db',
    storageBucket: 'academic-advisor-assistant-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr-hHRSk8iIArGZjxt237W1ZO8UZPBCAw',
    appId: '1:759792061333:ios:8363c0da105e4fc0a9049c',
    messagingSenderId: '759792061333',
    projectId: 'academic-advisor-assistant-db',
    storageBucket: 'academic-advisor-assistant-db.appspot.com',
    iosClientId: '759792061333-c9jgtkv7g31bj8hnua7j5sp701i64iat.apps.googleusercontent.com',
    iosBundleId: 'GP1G3.AcademicAdviser.academicAdviser',
  );
}
